### PR TITLE
DX: Product flavours for dev and release builds.

### LINKED ISSUE #33: DX: Product flavours for dev and release builds.
Right now dev builds of Otraku replaces the release build instead of creating a new app with a prefix.

### PR DESCRIPTION
**Pull request by Curstantine**
Fixes #33

1. Updated kotlin plugin as it wouldn't build for me.
2. Added icons to differentiate `release` and `dev` builds.
3. Moved from `GradleException` to `RuntimeException` as latter is no longer supported.

I'm pretty confused about how iOS handles the icons, so I didn't do any chagnes for that.

### CODE REVIEW

**Review by lotusgate — CHANGES_REQUESTED** [review]
I see you are using an image for the icon backgrounds? I think opting for a color is better. I used the flutter_launcher_icons package to generate the data for the release build. The same can be done for the dev one.
So can you remove this commit from the PR?

**Comment by Curstantine** [comment]
Should I remove those assets and commit the ones that depend on colors like you told, or should I just remove that commit?

**Comment by lotusgate** [comment]
If you don't mind the trouble, you can commit new ones for the dev build.
In that case, you can decide whether you want to copy-paste from `main` to `debug` or you will try with [flutter_launcher_icons](https://pub.dev/packages/flutter_launcher_icons).

**Review by lotusgate — APPROVED** [review]
Great, thanks for the PR!

**Pull request merged**
