### PR TITLE
Android changes.

### PR DESCRIPTION
**Pull request by KaloyanStoyanov06**
Modified the icon to be part of the new themed icons in android 13.

Made the navigation bar transparent so the app can be more beautiful and immersive.

### CODE REVIEW

**Comment by KaloyanStoyanov06** [comment]
I see that you have tried to make it transparent on the dev branch. But in order for that to work you need to add:
` SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);`.
And for samsung users you need to add in the config 
`systemNavigationBarContrastEnforced: false,`

**Comment by KaloyanStoyanov06** [comment]
Oh and sorry that I sent a PR for the main branch instead of the dev. But I think you can change it to be in the dev.

**Comment by lotusgate** [comment]
Hello, thanks for the help. I changed the base branch, but I had already worked on the transparent status bar, so there are some conflicts that need to be resolved. I recently added the transparency, but I didn't know about overriding the contrast, so that's a good catch. You will need to fix the formatting however - I keep the project's line length at 80.
I don't understand the change about the icons though - I use [flutter_launcher_icons](https://pub.dev/packages/flutter_launcher_icons) to generate the app icons. Material You dynamic coloring is not yet supported unfortunately, so I have to wait for it. But that's why I don't think the change is needed here. I've changed the background color, but it will remain static, so that won't be in line with m3. And some of the icon images are rounded, while (I believe), android launcher will deal with the shape clipping by themselves.

**Comment by KaloyanStoyanov06** [comment]
Hi again,
I will fix the formatting to be at 80. Sorry about that.
flutter_launcher_icons is outdated and I personally use a site named [IconKitchen](https://icon.kitchen/).
It gives you more customization and you just need to drag and drop the new icons.
The icons are better because they are up to date and support themed icons.

This is how it looks normal: 
image

And this is themed:
image

The rounded images I think are not used in modern android. It is a support for the older devices. But It's up to you. So I will remove them and leave it to you : ).

But can I ask you where I can put for the formatting to be at 80?

I will fix it later this evening. 
Thanks for the feedback

**Comment by lotusgate** [comment]
Don't worry, there's no hurry.
About the formatting, I use VS Code and in the settings I can configure the default formatting for the dart plugin. In general there's `dart format` and I think `flutter format`, but I don't know how to configure them directly.
For the icons, I think sharp squares to the job, the rest should be handled by the launcher (well, I haven't heard complaints at least). The default color, should be like the current one though, you've selected something purple-ish, but for now I think we should stick with the blue one.

**Comment by KaloyanStoyanov06** [comment]
I think everything is fixed. :)

**Comment by KaloyanStoyanov06** [comment]
I think everything is fixed : )

**Comment by lotusgate** [comment]
Ok, almost perfect, but I do have to return you for some things 😅
1. You only fixed the icons in `src/main` and not in `src/dev`
2. I see you've added the needed mipmap files for adaptive icons, but could you revert the `ic_launcher.png` images to the old ones? And are you sure the color used for the `ic_launcher_background.png` is `#0D161E`? It needs to be the same for consistency.

**Comment by KaloyanStoyanov06** [comment]
Oops i forgot about the dev folder. Sorry 😢.

I will fix these right now.

Btw I want to compliment you on your skill with Flutter. It's truly an insane app made from one man.

**Comment by lotusgate** [comment]
I think you've completely removed the images for the legacy icons, but honestly, I want to migrate to android 8.0 as the minimum supported version, so that's fine.
Now 2 funny nitpicks:
- You've reformatted `main.dart` with the long lines again, lmao
- In `src/dev/res` you should revert all changes in the `values` directory. The idea is that for debug builds the icon would be differently colored, so you can differentiate between a release and debug install.

Haha, thank you for the compliment! I've just sunk a ton of time into the app and it happened to pay off 😛

**Comment by KaloyanStoyanov06** [comment]
Damn, VSCode really making me commit again because of the auto format :D 
I am sorry for changing the values.

Sorry, It's just my first time working in other people repos.

**Comment by lotusgate** [comment]
Yea, np. Everything seems fine now.

**Comment by lotusgate** [comment]
Thanks for the help again

**Pull request merged**
