### PR TITLE
feat: Previews for themes in settings page.

### LINKED ISSUE #43: Feat: Theme previews in settings page.
Having previews for the themes will be quite nice.

Screenshot_20220727-191851_Otraku-dev

### PR DESCRIPTION
**Pull request by Curstantine**
closes #43

### CODE REVIEW

**Comment by Curstantine** [comment]
Not sure if it's a good idea to merge to master since the riverpod migration is still going on, tell me if I should re-pull

**Comment by Curstantine** [comment]
Screenshot_20220727-193329_Otraku-dev

**Comment by Curstantine** [comment]
I feel like I should use a font with lower priority font size/color.

**Comment by lotusgate** [comment]
will finish reviewing in 20 minutes; I will request a few changes

**Review by lotusgate — CHANGES_REQUESTED** [review]
Looks pretty cool, but I have a few requests (sorry, if it's too much):
1. In `SettingsAppTab`, taking `colorSchemeMap` outside of the build method isn't useful, so I think you should revert that change (including the type inference in the declaration)
2. In the card, can you replace the types on lines 21, 22 with `final`. Also, using `inverseSurface` is a good idea, but I haven't supplied that value to my custom themes😅. Maybe use `surfaceVariant`. On line 88 use `const Spacer()` instead (and in that case, I think you can remove the `mainAxisAlignment` argument of the surrounding `Column`). On lines 54 and 73 use `const`. Replace `Container` with `Padding` on line 43 and with `SizedBox` on line 89. And instead of the 3 shapes, put a larger, circular, floating action button to the right. On line 118, you can remove the `style` property, as `Text` uses `bodyText2` by default iirc. Lastly, in the newest version of dart, you can propagate values to the base class constructor, without calling it - on line 7, use `super.key` instead of `Key? key` and remove the call to the super constructor
4. In the preview row, there's no need to override `initState` and `disposeState` if you aren't going to do something there. On line 48, use the `subtitle1` style for the text. Use `SizedBox` instead of `Container` on line 49. And while the key property is generally useful, I avoid putting it in my custom widgets, unless I happen to need it, so can you remove `key` from the row?
6. In this codebase, I always add trailing commas, unless the whole thing can fit on one line (and the editor formats everything). For example, in the card, on lines 35-38, there should be a comma after the `Consts.borderRadiusMin`, but there's no need for a comma after the `Border.all` constructor, as it fits on one line
7. Can you merge `theme_preview.dart` and `theme_preview_row.dart` into just `themes_preview.dart`, rename `ThemePreview` to `_ThemeCard` and `ThemePreviewRow` to `ThemesPreview` (and place it above the card)
8. Finally, I think there's no need to pass so much from `SettingsAppTab` to the row widget. It only needs `colorSchemeMap` and a `bool` that determines if it's for dark themes or not. With just that, it can determine the title, the currently selected theme (from `Settings()`), what to do when a new theme is selected (modify `Settings()`) and its list of themes (it will create `darkThemes`/`lightThemes` by itself, so you can move them out of `SettingsAppTab`)

**Comment by Curstantine** [comment]
Haha, I'll fix these and push it. 😅

**Comment by lotusgate** [comment]
oh and yeah, use the dev branch

**Comment by Curstantine** [comment]
I didn't remove the small shapes (I feel like they *should* be there), but I did some changes and added a FAB.

Screenshot_20220727-233232_Otraku-dev

**Review by lotusgate — APPROVED** [review]
Nice job 😊

**Comment by lotusgate** [comment]
I just realised that this introduces a different behaviour for how themes are handled - before, you could use a dark theme even in light mode (and vice versa). Now I will have to make more light themes 🤔

**Comment by Curstantine** [comment]
Ah sorry, I forgot to mention that. Since you can explicitly change the "mode", it made no sense for me to add both dark and light themes in both the categories.

**Comment by lotusgate** [comment]
Yeah, I was planning to do this change anyway. I just didn't realise this pr would introduce it 😅

**Pull request merged**
